spring:
  # 数据库
  datasource:
    druid:
      # 驱动
      driver-class-name: org.postgresql.Driver
      # 连接路径
      url: jdbc:postgresql://192.168.31.201:15400/postgres?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
      # 用户名
      username: quanta
      # 密码
      password: 1q2w3e!Q@W#E
      # 初始建立连接数量
      initialSize: 5
      # 最小连接数量
      minIdle: 5
      # 最大连接数量
      maxActive: 20
      # 获取连接最大等待时间，毫秒
      maxWait: 10000
      # 申请连接时检测连接是否有效
      testOnBorrow: true
      # 归还连接时检测连接是否有效
      testOnReturn: false
      # 配置间隔检测连接是否有效的时间（单位是毫秒）
      timeBetweenEvictionRunsMillis: 60000
      # 连接在连接池的最小生存时间（毫秒）
      minEvictableIdleTimeMillis: 300000

